use crate::codegen::naming::to_pascal_case;
use crate::codegen::schema::{FieldModel, SchemaModel, TableModel};

pub fn map_cs_type(field: &FieldModel) -> &'static str {
    let t = field.db_type.as_str();
    match t {
        "UUID" => "Guid",
        "VARCHAR" | "TEXT" | "CHAR" => "string",
        "INT" | "INTEGER" => "int",
        "BIGINT" => "long",
        "SMALLINT" => "short",
        "BOOLEAN" | "BOOL" => "bool",
        "TIMESTAMPTZ" | "TIMESTAMP" | "DATETIME" => "DateTime",
        "DATE" => "DateOnly",
        "TIME" => "TimeOnly",
        "DECIMAL" | "NUMERIC" => "decimal",
        "FLOAT" | "REAL" => "float",
        "DOUBLE" => "double",
        "JSON" | "JSONB" => "string",
        "BYTEA" | "BLOB" => "byte[]",
        _ => "string",
    }
}

pub fn generate_csharp_models(schema: &SchemaModel, namespace: &str) -> Vec<(String, String)> {
    let mut files = Vec::new();

    for table in &schema.tables {
        let filename = format!("{}.cs", table.entity_name);
        let content = generate_single_cs_class(schema, table, namespace);
        files.push((filename, content));
    }

    // DbContext class
    let db_context_content = generate_cs_dbcontext(schema, namespace);
    files.push(("MigraDbContext.cs".to_string(), db_context_content));

    files
}

fn generate_single_cs_class(schema: &SchemaModel, table: &TableModel, namespace: &str) -> String {
    let mut out = String::new();
    out.push_str("// <auto-generated> by MigraDB. DO NOT EDIT. </auto-generated>\n");
    out.push_str("using System;\n");
    out.push_str("using System.Collections.Generic;\n");
    out.push_str("using System.ComponentModel.DataAnnotations;\n");
    out.push_str("using System.ComponentModel.DataAnnotations.Schema;\n\n");
    out.push_str(&format!("namespace {}\n{{\n", namespace));

    out.push_str(&format!("    [Table(\"{}\")]\n", table.raw_name));
    out.push_str(&format!("    public partial class {}\n    {{\n", table.entity_name));

    // Fields
    for f in &table.fields {
        let prop_name = to_pascal_case(&f.name);
        let base_type = map_cs_type(f);

        let cs_type = if f.not_null || f.primary {
            base_type.to_string()
        } else if base_type == "string" || base_type == "byte[]" {
            format!("{}?", base_type)
        } else {
            format!("{}?", base_type)
        };

        if f.primary {
            out.push_str("        [Key]\n");
        }
        out.push_str(&format!("        [Column(\"{}\")]\n", f.name));

        if f.not_null && !f.primary && base_type == "string" {
            out.push_str("        [Required]\n");
        }
        if let Some(size) = &f.size {
            if f.db_type == "VARCHAR" || f.db_type == "CHAR" {
                out.push_str(&format!("        [MaxLength({})]\n", size));
            }
        }

        let init_val = if (f.not_null || f.primary) && base_type == "string" {
            " = null!;"
        } else {
            ""
        };

        out.push_str(&format!(
            "        public {} {} {{ get; set; }}{}\n\n",
            cs_type, prop_name, init_val
        ));
    }

    // Navigation Properties
    let incoming = schema.incoming_relationships(&table.id);
    let outgoing = schema.outgoing_relationships(&table.id);

    if !incoming.is_empty() || !outgoing.is_empty() {
        out.push_str("        #region Navigation Properties\n\n");

        for rel in incoming {
            if let Some(parent) = schema.find_table_by_id(&rel.parent_table_id) {
                if let Some(child_f) = schema.find_field(&table.id, &rel.child_field_id) {
                    let fk_prop = to_pascal_case(&child_f.name);
                    out.push_str(&format!("        [ForeignKey(\"{}\")]\n", fk_prop));
                    out.push_str(&format!(
                        "        public virtual {}? {} {{ get; set; }}\n\n",
                        parent.entity_name, parent.entity_name
                    ));
                }
            }
        }

        for rel in outgoing {
            if let Some(child) = schema.find_table_by_id(&rel.child_table_id) {
                let child_clean = &child.entity_name;
                let plural_name = if child_clean.ends_with('y') && !child_clean.ends_with("ey") {
                    format!("{}ies", &child_clean[..child_clean.len() - 1])
                } else if child_clean.ends_with('s') || child_clean.ends_with("ch") || child_clean.ends_with("sh") {
                    format!("{}es", child_clean)
                } else {
                    format!("{}s", child_clean)
                };

                let prop_name = to_pascal_case(&plural_name);
                out.push_str(&format!(
                    "        public virtual ICollection<{}> {} {{ get; set; }} = new List<{}>();\n\n",
                    child.entity_name, prop_name, child.entity_name
                ));
            }
        }

        out.push_str("        #endregion\n");
    }

    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn generate_cs_dbcontext(schema: &SchemaModel, namespace: &str) -> String {
    let mut out = String::new();
    out.push_str("// <auto-generated> by MigraDB. DO NOT EDIT. </auto-generated>\n");
    out.push_str("using System;\n");
    out.push_str("using Microsoft.EntityFrameworkCore;\n\n");
    out.push_str(&format!("namespace {}\n{{\n", namespace));
    out.push_str("    public partial class MigraDbContext : DbContext\n    {\n");
    out.push_str("        public MigraDbContext(DbContextOptions<MigraDbContext> options) : base(options) { }\n\n");

    for table in &schema.tables {
        let child_clean = &table.entity_name;
        let plural_name = if child_clean.ends_with('y') && !child_clean.ends_with("ey") {
            format!("{}ies", &child_clean[..child_clean.len() - 1])
        } else if child_clean.ends_with('s') || child_clean.ends_with("ch") || child_clean.ends_with("sh") {
            format!("{}es", child_clean)
        } else {
            format!("{}s", child_clean)
        };
        let set_name = to_pascal_case(&plural_name);
        out.push_str(&format!(
            "        public virtual DbSet<{}> {} {{ get; set; }} = null!;\n",
            table.entity_name, set_name
        ));
    }

    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

