use crate::codegen::naming::{to_go_field_name, to_pascal_case, to_snake_case};
use crate::codegen::schema::{FieldModel, SchemaModel, TableModel};

pub fn map_go_type(field: &FieldModel) -> (&'static str, bool, bool, bool) {
    // Returns (type_name, is_uuid, is_time, is_json)
    let t = field.db_type.as_str();
    match t {
        "UUID" => ("uuid.UUID", true, false, false),
        "VARCHAR" | "TEXT" | "CHAR" => ("string", false, false, false),
        "INT" | "INTEGER" => ("int", false, false, false),
        "BIGINT" => ("int64", false, false, false),
        "SMALLINT" => ("int16", false, false, false),
        "BOOLEAN" | "BOOL" => ("bool", false, false, false),
        "TIMESTAMPTZ" | "TIMESTAMP" | "DATETIME" | "DATE" => ("time.Time", false, true, false),
        "TIME" => ("string", false, false, false),
        "DECIMAL" | "NUMERIC" | "FLOAT" | "DOUBLE" | "REAL" => ("float64", false, false, false),
        "JSON" | "JSONB" => ("json.RawMessage", false, false, true),
        "BYTEA" | "BLOB" => ("[]byte", false, false, false),
        _ => ("string", false, false, false),
    }
}

pub fn generate_go_models(schema: &SchemaModel, pkg_name: &str) -> Vec<(String, String)> {
    // Returns Vec<(filename, content)>
    let mut files = Vec::new();

    for table in &schema.tables {
        let filename = format!("{}.go", to_snake_case(&table.entity_name));
        let content = generate_single_go_table(schema, table, pkg_name);
        files.push((filename, content));
    }

    files
}

fn generate_single_go_table(schema: &SchemaModel, table: &TableModel, pkg_name: &str) -> String {
    let mut needs_uuid = false;
    let mut needs_time = false;
    let mut needs_json = false;

    for f in &table.fields {
        let (_, is_u, is_t, is_j) = map_go_type(f);
        if is_u {
            needs_uuid = true;
        }
        if is_t {
            needs_time = true;
        }
        if is_j {
            needs_json = true;
        }
    }

    let mut out = String::new();
    out.push_str("// Code generated by MigraDB. DO NOT EDIT.\n\n");
    out.push_str(&format!("package {}\n\n", pkg_name));

    // Imports
    let mut imports = Vec::new();
    if needs_json {
        imports.push("\"encoding/json\"");
    }
    if needs_time {
        imports.push("\"time\"");
    }
    if needs_uuid {
        imports.push("\"github.com/google/uuid\"");
    }

    if !imports.is_empty() {
        out.push_str("import (\n");
        for imp in imports {
            out.push_str(&format!("\t{}\n", imp));
        }
        out.push_str(")\n\n");
    }

    // Table Comment & Struct
    if let Some(comment) = &table.comment {
        out.push_str(&format!("// {} {}\n", table.entity_name, comment));
    } else {
        out.push_str(&format!(
            "// {} maps to database table `{}`.\n",
            table.entity_name, table.raw_name
        ));
    }

    out.push_str(&format!("type {} struct {{\n", table.entity_name));

    // Fields
    for f in &table.fields {
        let field_name = to_go_field_name(&f.name);
        let (base_type, _, _, _) = map_go_type(f);

        let go_type = if f.not_null || f.primary {
            base_type.to_string()
        } else if base_type.starts_with("[]") {
            base_type.to_string()
        } else {
            format!("*{}", base_type)
        };

        let tag = format!("`json:\"{}\" db:\"{}\"`", f.name, f.name);
        out.push_str(&format!("\t{:<18} {:<18} {}\n", field_name, go_type, tag));
    }

    // Navigation Properties (Relations)
    let incoming = schema.incoming_relationships(&table.id);
    let outgoing = schema.outgoing_relationships(&table.id);

    if !incoming.is_empty() || !outgoing.is_empty() {
        out.push_str("\n\t// Navigation Properties\n");
        let mut used_names = std::collections::HashSet::new();
        for f in &table.fields {
            used_names.insert(to_go_field_name(&f.name));
        }

        // Incoming: Many-to-One (Parent entity)
        for rel in incoming {
            if let Some(parent) = schema.find_table_by_id(&rel.parent_table_id) {
                let mut prop_name = if let Some(cf) = schema.find_field(&table.id, &rel.child_field_id) {
                    if cf.name.ends_with("_id") && cf.name != "id" {
                        to_pascal_case(&cf.name[..cf.name.len() - 3])
                    } else {
                        parent.entity_name.clone()
                    }
                } else {
                    parent.entity_name.clone()
                };

                // If prop_name collides with an existing field, prefer parent.entity_name
                if used_names.contains(&prop_name) && !used_names.contains(&parent.entity_name) {
                    prop_name = parent.entity_name.clone();
                }

                let mut final_name = prop_name;
                let mut counter = 2;
                while used_names.contains(&final_name) {
                    final_name = format!("{}{}", final_name, counter);
                    counter += 1;
                }
                used_names.insert(final_name.clone());

                let prop_type = format!("*{}", parent.entity_name);
                let json_name = to_snake_case(&final_name);
                let tag = format!("`json:\"{},omitempty\" db:\"-\"`", json_name);
                out.push_str(&format!("\t{:<18} {:<18} {}\n", final_name, prop_type, tag));
            }
        }

        // Outgoing: One-to-Many (Children entities)
        for rel in outgoing {
            if let Some(child) = schema.find_table_by_id(&rel.child_table_id) {
                let child_clean = &child.entity_name;
                // Pluralize child entity name for collection
                let plural_name = if child_clean.ends_with('y') && !child_clean.ends_with("ey") {
                    format!("{}ies", &child_clean[..child_clean.len() - 1])
                } else if child_clean.ends_with('s') || child_clean.ends_with("ch") || child_clean.ends_with("sh") {
                    format!("{}es", child_clean)
                } else {
                    format!("{}s", child_clean)
                };

                let prop_name = to_pascal_case(&plural_name);
                if used_names.contains(&prop_name) {
                    continue;
                }
                used_names.insert(prop_name.clone());

                let prop_type = format!("[]{}", child.entity_name);
                let json_name = to_snake_case(&plural_name);
                let tag = format!("`json:\"{},omitempty\" db:\"-\"`", json_name);
                out.push_str(&format!("\t{:<18} {:<18} {}\n", prop_name, prop_type, tag));
            }
        }
    }

    out.push_str("}\n");
    out
}

