use crate::codegen::naming::{to_camel_case, to_snake_case};
use crate::codegen::schema::{FieldModel, SchemaModel, TableModel};

pub fn map_ts_type(field: &FieldModel) -> &'static str {
    let t = field.db_type.as_str();
    match t {
        "UUID" | "VARCHAR" | "TEXT" | "CHAR" | "TIME" => "string",
        "INT" | "INTEGER" | "BIGINT" | "SMALLINT" | "DECIMAL" | "NUMERIC" | "FLOAT" | "DOUBLE"
        | "REAL" => "number",
        "BOOLEAN" | "BOOL" => "boolean",
        "TIMESTAMPTZ" | "TIMESTAMP" | "DATETIME" | "DATE" => "Date",
        "JSON" | "JSONB" => "Record<string, any>",
        "BYTEA" | "BLOB" => "Uint8Array",
        _ => "any",
    }
}

pub fn generate_node_ts_models(schema: &SchemaModel) -> Vec<(String, String)> {
    let mut files = Vec::new();
    let mut export_names = Vec::new();

    for table in &schema.tables {
        let filename = format!("{}.ts", to_snake_case(&table.entity_name));
        let content = generate_single_ts_table(schema, table);
        files.push((filename, content));
        export_names.push((table.entity_name.clone(), to_snake_case(&table.entity_name)));
    }

    // index.ts exporting all interfaces
    let mut index_content = String::new();
    index_content.push_str("// Code generated by MigraDB. DO NOT EDIT.\n\n");
    for (entity, file) in export_names {
        index_content.push_str(&format!("export type {{ {} }} from './{}';\n", entity, file));
    }
    files.push(("index.ts".to_string(), index_content));

    files
}

fn generate_single_ts_table(schema: &SchemaModel, table: &TableModel) -> String {
    let mut out = String::new();
    out.push_str("// Code generated by MigraDB. DO NOT EDIT.\n\n");

    // Gather imported types from navigation properties
    let incoming = schema.incoming_relationships(&table.id);
    let outgoing = schema.outgoing_relationships(&table.id);

    let mut related_entities = Vec::new();
    for rel in &incoming {
        if let Some(parent) = schema.find_table_by_id(&rel.parent_table_id) {
            if parent.entity_name != table.entity_name && !related_entities.contains(&parent.entity_name) {
                related_entities.push(parent.entity_name.clone());
            }
        }
    }
    for rel in &outgoing {
        if let Some(child) = schema.find_table_by_id(&rel.child_table_id) {
            if child.entity_name != table.entity_name && !related_entities.contains(&child.entity_name) {
                related_entities.push(child.entity_name.clone());
            }
        }
    }

    for entity in related_entities {
        out.push_str(&format!(
            "import type {{ {} }} from './{}';\n",
            entity,
            to_snake_case(&entity)
        ));
    }
    if !incoming.is_empty() || !outgoing.is_empty() {
        out.push('\n');
    }

    if let Some(comment) = &table.comment {
        out.push_str(&format!("/** {} */\n", comment));
    } else {
        out.push_str(&format!(
            "/** Maps to database table `{}` */\n",
            table.raw_name
        ));
    }

    out.push_str(&format!("export interface {} {{\n", table.entity_name));

    // Fields
    for f in &table.fields {
        let field_name = to_camel_case(&f.name);
        let base_type = map_ts_type(f);

        let type_decl = if f.not_null || f.primary {
            format!("{}: {};", field_name, base_type)
        } else {
            format!("{}?: {} | null;", field_name, base_type)
        };

        if let Some(comment) = &f.comment {
            out.push_str(&format!("  /** {} */\n", comment));
        }
        out.push_str(&format!("  {}\n", type_decl));
    }

    // Navigation Properties
    if !incoming.is_empty() || !outgoing.is_empty() {
        out.push_str("\n  // Navigation Properties\n");

        for rel in incoming {
            if let Some(parent) = schema.find_table_by_id(&rel.parent_table_id) {
                let prop_name = to_camel_case(&parent.entity_name);
                out.push_str(&format!("  {}?: {};\n", prop_name, parent.entity_name));
            }
        }

        for rel in outgoing {
            if let Some(child) = schema.find_table_by_id(&rel.child_table_id) {
                let child_clean = &child.entity_name;
                let plural_name = if child_clean.ends_with('y') && !child_clean.ends_with("ey") {
                    format!("{}ies", &child_clean[..child_clean.len() - 1])
                } else if child_clean.ends_with('s') || child_clean.ends_with("ch") || child_clean.ends_with("sh") {
                    format!("{}es", child_clean)
                } else {
                    format!("{}s", child_clean)
                };

                let prop_name = to_camel_case(&plural_name);
                out.push_str(&format!("  {}?: {}[];\n", prop_name, child.entity_name));
            }
        }
    }

    out.push_str("}\n");
    out
}

