use crate::codegen::naming::to_snake_case;
use crate::codegen::schema::{FieldModel, SchemaModel, TableModel};

pub fn map_py_type(field: &FieldModel) -> (&'static str, &'static str) {
    // Returns (type_annotation, sqlalchemy_col_type)
    let t = field.db_type.as_str();
    match t {
        "UUID" => ("UUID", "PG_UUID(as_uuid=True)"),
        "VARCHAR" | "CHAR" => {
            if field.size.is_some() {
                ("str", "String")
            } else {
                ("str", "String(255)")
            }
        }
        "TEXT" => ("str", "Text"),
        "INT" | "INTEGER" => ("int", "Integer"),
        "BIGINT" => ("int", "BigInteger"),
        "SMALLINT" => ("int", "SmallInteger"),
        "BOOLEAN" | "BOOL" => ("bool", "Boolean"),
        "TIMESTAMPTZ" | "TIMESTAMP" | "DATETIME" => ("datetime", "DateTime(timezone=True)"),
        "DATE" => ("date", "Date"),
        "TIME" => ("time", "Time"),
        "DECIMAL" | "NUMERIC" => ("Decimal", "Numeric"),
        "FLOAT" | "DOUBLE" | "REAL" => ("float", "Float"),
        "JSON" | "JSONB" => ("dict", "JSONB"),
        "BYTEA" | "BLOB" => ("bytes", "LargeBinary"),
        _ => ("str", "String"),
    }
}

pub fn generate_python_models(schema: &SchemaModel) -> Vec<(String, String)> {
    let mut files = Vec::new();

    // Generate single models.py containing Base and all models
    let mut out = String::new();
    out.push_str("# Code generated by MigraDB. DO NOT EDIT.\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from datetime import datetime, date, time\n");
    out.push_str("from decimal import Decimal\n");
    out.push_str("from typing import Optional, List, Any\n");
    out.push_str("from uuid import UUID\n\n");
    out.push_str("from sqlalchemy import (\n");
    out.push_str("    BigInteger,\n");
    out.push_str("    Boolean,\n");
    out.push_str("    Date,\n");
    out.push_str("    DateTime,\n");
    out.push_str("    Float,\n");
    out.push_str("    ForeignKey,\n");
    out.push_str("    Integer,\n");
    out.push_str("    LargeBinary,\n");
    out.push_str("    Numeric,\n");
    out.push_str("    SmallInteger,\n");
    out.push_str("    String,\n");
    out.push_str("    Text,\n");
    out.push_str("    Time,\n");
    out.push_str(")\n");
    out.push_str("from sqlalchemy.dialects.postgresql import UUID as PG_UUID, JSONB\n");
    out.push_str("from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship\n\n\n");
    out.push_str("class Base(DeclarativeBase):\n");
    out.push_str("    pass\n\n");

    for table in &schema.tables {
        out.push_str(&generate_single_py_class(schema, table));
        out.push_str("\n\n");
    }

    files.push(("models.py".to_string(), out));

    // __init__.py exporting Base and all models
    let mut init_py = String::new();
    init_py.push_str("# Code generated by MigraDB. DO NOT EDIT.\n");
    init_py.push_str("from .models import Base");
    for table in &schema.tables {
        init_py.push_str(&format!(", {}", table.entity_name));
    }
    init_py.push_str("\n\n__all__ = [\"Base\"");
    for table in &schema.tables {
        init_py.push_str(&format!(", \"{}\"", table.entity_name));
    }
    init_py.push_str("]\n");
    files.push(("__init__.py".to_string(), init_py));

    files
}

fn generate_single_py_class(schema: &SchemaModel, table: &TableModel) -> String {
    let mut out = String::new();
    out.push_str(&format!("class {}(Base):\n", table.entity_name));
    out.push_str(&format!("    __tablename__ = \"{}\"\n\n", table.raw_name));

    // Fields
    for f in &table.fields {
        let field_name = to_snake_case(&f.name);
        let (py_type, col_type) = map_py_type(f);

        let type_ann = if f.not_null || f.primary {
            format!("Mapped[{}]", py_type)
        } else {
            format!("Mapped[Optional[{}]]", py_type)
        };

        let mut col_args = Vec::new();

        // Foreign key check
        let is_fk = schema
            .incoming_relationships(&table.id)
            .into_iter()
            .find(|r| r.child_field_id == f.id);

        if let Some(rel) = is_fk {
            if let Some(parent) = schema.find_table_by_id(&rel.parent_table_id) {
                if let Some(parent_f) = schema.find_field(&rel.parent_table_id, &rel.parent_field_id) {
                    col_args.push(format!("ForeignKey(\"{}.{}\")", parent.raw_name, parent_f.name));
                }
            }
        } else if let Some(size) = &f.size {
            if f.db_type == "VARCHAR" || f.db_type == "CHAR" {
                col_args.push(format!("String({})", size));
            } else {
                col_args.push(col_type.to_string());
            }
        } else {
            col_args.push(col_type.to_string());
        }

        if f.primary {
            col_args.push("primary_key=True".to_string());
        }
        if !f.not_null && !f.primary {
            col_args.push("nullable=True".to_string());
        }

        out.push_str(&format!(
            "    {}: {} = mapped_column({})\n",
            field_name,
            type_ann,
            col_args.join(", ")
        ));
    }

    // Navigation Properties
    let incoming = schema.incoming_relationships(&table.id);
    let outgoing = schema.outgoing_relationships(&table.id);

    if !incoming.is_empty() || !outgoing.is_empty() {
        out.push_str("\n    # Navigation Properties\n");

        for rel in incoming {
            if let Some(parent) = schema.find_table_by_id(&rel.parent_table_id) {
                let prop_name = to_snake_case(&parent.entity_name);
                out.push_str(&format!(
                    "    {}: Mapped[Optional[\"{}\"]] = relationship()\n",
                    prop_name, parent.entity_name
                ));
            }
        }

        for rel in outgoing {
            if let Some(child) = schema.find_table_by_id(&rel.child_table_id) {
                let child_clean = &child.entity_name;
                let plural_name = if child_clean.ends_with('y') && !child_clean.ends_with("ey") {
                    format!("{}ies", &child_clean[..child_clean.len() - 1])
                } else if child_clean.ends_with('s') || child_clean.ends_with("ch") || child_clean.ends_with("sh") {
                    format!("{}es", child_clean)
                } else {
                    format!("{}s", child_clean)
                };

                let prop_name = to_snake_case(&plural_name);
                out.push_str(&format!(
                    "    {}: Mapped[List[\"{}\"]] = relationship()\n",
                    prop_name, child.entity_name
                ));
            }
        }
    }

    out
}

