use crate::codegen::naming::to_snake_case;
use crate::codegen::schema::{FieldModel, SchemaModel, TableModel};

fn map_rust_type(field: &FieldModel) -> (&'static str, bool, bool, bool) {
    // Returns (type_str, needs_chrono, needs_uuid, needs_json)
    let t = field.db_type.to_uppercase();
    match t.as_str() {
        "UUID" => ("uuid::Uuid", false, true, false),
        "VARCHAR" | "TEXT" | "CHAR" => ("String", false, false, false),
        "INT" | "INTEGER" | "INT4" => ("i32", false, false, false),
        "BIGINT" | "INT8" => ("i64", false, false, false),
        "SMALLINT" | "INT2" => ("i16", false, false, false),
        "BOOLEAN" | "BOOL" => ("bool", false, false, false),
        "TIMESTAMPTZ" | "TIMESTAMP" | "DATETIME" => ("chrono::DateTime<chrono::Utc>", true, false, false),
        "DATE" => ("chrono::NaiveDate", true, false, false),
        "TIME" => ("chrono::NaiveTime", true, false, false),
        "DECIMAL" | "NUMERIC" | "FLOAT" | "DOUBLE" | "REAL" => ("f64", false, false, false),
        "JSON" | "JSONB" => ("serde_json::Value", false, false, true),
        "BYTEA" | "BLOB" => ("Vec<u8>", false, false, false),
        _ => ("String", false, false, false),
    }
}

fn sanitize_rust_ident(name: &str) -> String {
    let s = to_snake_case(name);
    match s.as_str() {
        "as" | "break" | "const" | "continue" | "crate" | "else" | "enum" | "extern" | "false"
        | "fn" | "for" | "if" | "impl" | "in" | "let" | "loop" | "match" | "mod" | "move"
        | "mut" | "pub" | "ref" | "return" | "self" | "Self" | "static" | "struct" | "super"
        | "trait" | "true" | "type" | "unsafe" | "use" | "where" | "while" | "async" | "await"
        | "dyn" => format!("r#{}", s),
        _ => s,
    }
}

pub fn generate_rust_models(schema: &SchemaModel) -> Vec<(String, String)> {
    let mut files = Vec::new();
    let mut mod_lines = Vec::new();
    let mut export_lines = Vec::new();

    for table in &schema.tables {
        let mod_name = to_snake_case(&table.entity_name);
        let filename = format!("{}.rs", mod_name);
        let content = generate_single_rust_struct(schema, table);
        files.push((filename, content));

        mod_lines.push(format!("pub mod {};", mod_name));
        export_lines.push(format!("pub use {}::{};", mod_name, table.entity_name));
    }

    // Generate mod.rs
    let mut mod_content = String::new();
    mod_content.push_str("// <auto-generated> by MigraDB. DO NOT EDIT. </auto-generated>\n\n");
    for line in mod_lines {
        mod_content.push_str(&line);
        mod_content.push('\n');
    }
    mod_content.push('\n');
    for line in export_lines {
        mod_content.push_str(&line);
        mod_content.push('\n');
    }

    files.push(("mod.rs".to_string(), mod_content));
    files
}

fn generate_single_rust_struct(_schema: &SchemaModel, table: &TableModel) -> String {
    let mut out = String::new();
    out.push_str("// <auto-generated> by MigraDB. DO NOT EDIT. </auto-generated>\n\n");
    out.push_str("use serde::{Deserialize, Serialize};\n");

    let mut needs_chrono = false;
    let mut needs_uuid = false;
    let mut needs_json = false;

    for field in &table.fields {
        let (_, c, u, j) = map_rust_type(field);
        if c {
            needs_chrono = true;
        }
        if u {
            needs_uuid = true;
        }
        if j {
            needs_json = true;
        }
    }

    if needs_chrono {
        out.push_str("use chrono::{DateTime, NaiveDate, NaiveTime, Utc};\n");
    }
    if needs_uuid {
        out.push_str("use uuid::Uuid;\n");
    }
    if needs_json {
        out.push_str("use serde_json::Value as JsonValue;\n");
    }

    out.push('\n');
    if let Some(comment) = &table.comment {
        out.push_str(&format!("/// {}\n", comment));
    }
    out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
    out.push_str("#[cfg_attr(feature = \"sqlx\", derive(sqlx::FromRow))]\n");
    out.push_str(&format!("pub struct {} {{\n", table.entity_name));

    for field in &table.fields {
        let (raw_type, _, _, is_json) = map_rust_type(field);
        let type_name = if is_json { "JsonValue" } else { raw_type };
        let is_nullable = !field.not_null && !field.primary;
        let final_type = if is_nullable {
            format!("Option<{}>", type_name)
        } else {
            type_name.to_string()
        };

        let field_ident = sanitize_rust_ident(&field.name);
        if let Some(comment) = &field.comment {
            out.push_str(&format!("    /// {}\n", comment));
        }

        // If field name was renamed for Rust conventions (e.g. from camelCase or if raw is different)
        if field.name != field_ident {
            out.push_str(&format!("    #[serde(rename = \"{}\")]\n", field.name));
            out.push_str(&format!("    #[cfg_attr(feature = \"sqlx\", sqlx(rename = \"{}\"))]\n", field.name));
        }

        out.push_str(&format!("    pub {}: {},\n", field_ident, final_type));
    }

    out.push_str("}\n");
    out
}
