use crate::codegen::schema::SchemaModel;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SqlDialect {
    Postgres,
    MySql,
    Sqlite,
}

impl SqlDialect {
    pub fn parse(s: &str) -> Self {
        match s.to_lowercase().trim() {
            "mysql" | "mariadb" => Self::MySql,
            "sqlite" | "sqlite3" => Self::Sqlite,
            _ => Self::Postgres,
        }
    }
}

pub fn generate_sql_ddl(schema: &SchemaModel, dialect_str: &str) -> Vec<(String, String)> {
    let dialect = SqlDialect::parse(dialect_str);
    let mut out = String::new();

    out.push_str("-- -----------------------------------------------------------------------------\n");
    out.push_str("-- Schema DDL generated by MigraDB. DO NOT EDIT.\n");
    out.push_str(&format!("-- Dialect: {:?}\n", dialect));
    out.push_str("-- -----------------------------------------------------------------------------\n\n");

    if dialect == SqlDialect::Postgres {
        out.push_str("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";\n\n");
    } else if dialect == SqlDialect::Sqlite {
        out.push_str("PRAGMA foreign_keys = ON;\n\n");
    }

    // Topological sort or iterate tables
    for table in &schema.tables {
        out.push_str(&format!("CREATE TABLE IF NOT EXISTS {} (\n", table.raw_name));

        let mut lines = Vec::new();
        let mut primary_keys = Vec::new();

        for field in &table.fields {
            if field.primary {
                primary_keys.push(field.name.clone());
            }

            let mut col_def = format!("    {}", field.name);
            let mapped_type = map_sql_type(&field.db_type, field.size.as_deref(), field.primary, dialect);
            col_def.push_str(&format!(" {}", mapped_type));

            if field.not_null && !field.primary {
                col_def.push_str(" NOT NULL");
            }

            if field.unique && !field.primary {
                col_def.push_str(" UNIQUE");
            }

            if let Some(def) = &field.default_value {
                if !def.is_empty() {
                    col_def.push_str(&format!(" DEFAULT {}", def));
                }
            }

            lines.push(col_def);
        }

        // Primary key constraint if composite or not auto-handled
        if !primary_keys.is_empty() {
            // For SQLite and MySQL, if not inline
            if dialect == SqlDialect::Postgres || primary_keys.len() > 1 {
                lines.push(format!("    PRIMARY KEY ({})", primary_keys.join(", ")));
            } else if dialect == SqlDialect::MySql {
                lines.push(format!("    PRIMARY KEY ({})", primary_keys.join(", ")));
            }
        }

        // Foreign keys for incoming relationships
        let incoming = schema.incoming_relationships(&table.id);
        for rel in incoming {
            if let (Some(parent_tbl), Some(child_fld), Some(parent_fld)) = (
                schema.find_table_by_id(&rel.parent_table_id),
                schema.find_field(&table.id, &rel.child_field_id),
                schema.find_field(&rel.parent_table_id, &rel.parent_field_id),
            ) {
                let fk_name = format!("fk_{}_{}", table.raw_name, child_fld.name);
                lines.push(format!(
                    "    CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({}) ON DELETE CASCADE ON UPDATE CASCADE",
                    fk_name, child_fld.name, parent_tbl.raw_name, parent_fld.name
                ));
            }
        }

        out.push_str(&lines.join(",\n"));
        out.push_str("\n);\n\n");
    }

    let filename = match dialect {
        SqlDialect::Postgres => "schema.postgres.sql",
        SqlDialect::MySql => "schema.mysql.sql",
        SqlDialect::Sqlite => "schema.sqlite.sql",
    };

    vec![
        (filename.to_string(), out.clone()),
        ("schema.sql".to_string(), out),
    ]
}

pub fn map_sql_type(raw_type: &str, size: Option<&str>, is_primary: bool, dialect: SqlDialect) -> String {
    let t = raw_type.to_uppercase();
    match dialect {
        SqlDialect::Postgres => match t.as_str() {
            "INT" | "INTEGER" if is_primary => "SERIAL".to_string(),
            "BIGINT" if is_primary => "BIGSERIAL".to_string(),
            "UUID" => "UUID".to_string(),
            "VARCHAR" => format!("VARCHAR({})", size.unwrap_or("255")),
            "TEXT" => "TEXT".to_string(),
            "INT" | "INTEGER" | "INT4" => "INTEGER".to_string(),
            "BIGINT" | "INT8" => "BIGINT".to_string(),
            "SMALLINT" | "INT2" => "SMALLINT".to_string(),
            "BOOLEAN" | "BOOL" => "BOOLEAN".to_string(),
            "TIMESTAMPTZ" | "TIMESTAMP" => "TIMESTAMPTZ".to_string(),
            "DATE" => "DATE".to_string(),
            "TIME" => "TIME".to_string(),
            "DECIMAL" | "NUMERIC" => size.map(|s| format!("NUMERIC({})", s)).unwrap_or_else(|| "NUMERIC".to_string()),
            "FLOAT" | "DOUBLE" | "REAL" => "DOUBLE PRECISION".to_string(),
            "JSON" | "JSONB" => "JSONB".to_string(),
            "BYTEA" | "BLOB" => "BYTEA".to_string(),
            other => other.to_string(),
        },
        SqlDialect::MySql => match t.as_str() {
            "INT" | "INTEGER" if is_primary => "INT AUTO_INCREMENT".to_string(),
            "BIGINT" if is_primary => "BIGINT AUTO_INCREMENT".to_string(),
            "UUID" => "VARCHAR(36)".to_string(),
            "VARCHAR" => format!("VARCHAR({})", size.unwrap_or("255")),
            "TEXT" => "TEXT".to_string(),
            "INT" | "INTEGER" => "INT".to_string(),
            "BIGINT" => "BIGINT".to_string(),
            "SMALLINT" => "SMALLINT".to_string(),
            "BOOLEAN" | "BOOL" => "TINYINT(1)".to_string(),
            "TIMESTAMPTZ" | "TIMESTAMP" | "DATETIME" => "DATETIME".to_string(),
            "DATE" => "DATE".to_string(),
            "TIME" => "TIME".to_string(),
            "DECIMAL" | "NUMERIC" => size.map(|s| format!("DECIMAL({})", s)).unwrap_or_else(|| "DECIMAL(10,2)".to_string()),
            "FLOAT" | "DOUBLE" | "REAL" => "DOUBLE".to_string(),
            "JSON" | "JSONB" => "JSON".to_string(),
            "BYTEA" | "BLOB" => "LONGBLOB".to_string(),
            other => other.to_string(),
        },
        SqlDialect::Sqlite => match t.as_str() {
            "INT" | "INTEGER" | "BIGINT" if is_primary => "INTEGER PRIMARY KEY AUTOINCREMENT".to_string(),
            "INT" | "INTEGER" | "BIGINT" | "SMALLINT" | "BOOLEAN" | "BOOL" => "INTEGER".to_string(),
            "DECIMAL" | "NUMERIC" | "FLOAT" | "DOUBLE" | "REAL" => "REAL".to_string(),
            "BYTEA" | "BLOB" => "BLOB".to_string(),
            _ => "TEXT".to_string(),
        },
    }
}
