/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Migration {
  version: string
  name: string
}
export interface MigrationStatus {
  version: string
  name: string
  applied: boolean
  appliedAt?: string
}
export interface RunResult {
  success: boolean
  applied: number
  migrations: Array<Migration>
  error?: string
}
export interface StatusResult {
  success: boolean
  migrations: Array<MigrationStatus>
  error?: string
}
export interface CreateResult {
  success: boolean
  path: string
  error?: string
}
export interface RemoveResult {
  success: boolean
  removed?: string
  message?: string
  error?: string
}
export interface GenerateResult {
  success: boolean
  files: Array<string>
  error?: string
}
export declare function generateModels(schemaPath: string, targetLang: string, outputDir: string, pkgOrNamespace?: string | undefined | null): GenerateResult
export declare class Migrator {
  constructor(migrationsDir: string)
  generateModels(schemaPath: string, targetLang: string, outputDir: string, pkgOrNamespace?: string | undefined | null): GenerateResult
  run(): RunResult
  status(): StatusResult
  create(name: string, content: string): CreateResult
  removePending(): RemoveResult
}
